[tasks.test]
depends = ["gen-tests"]
run = "./st_syntax_tests/syntax_tests | python parse_syntax_test_output.py -c '//'"

[tasks.gen-tests]
run = "./yaml2syntaxtest.py yaml_tests tests"

[tasks.link]
run = """
mkdir "$(realpath st_syntax_tests)/Data/Packages/Kotlin" && \
ln -vs "$(realpath "Kotlin.sublime-syntax")" "$(realpath st_syntax_tests)/Data/Packages/Kotlin" && \
ln -vs "$(realpath "tests")" "$(realpath st_syntax_tests)/Data/Packages/Kotlin/tests"
"""
